### ISSUE TITLE
Firefox: "SyntaxError: class is a reserved identifier"

### ISSUE THREAD

**Issue by easimonenko** [2DKot/AI_Contester#2]
When I open in Firefox the page of the web interface, the application does not start and in console I see the error message in app.js:

SyntaxError: class is a reserved identifier app.js:10:0

The problem is that in **Firefox 44 not yet implemented support classes**.

**To avoid this problem, compile the application app.js in ES5.**

**Comment by easimonenko** [comment]
With the option "target": "es5" I get the message compile error:

```
C:/Temp/AI_Contester/web/typings/whatwg-fetch/whatwg-fetch.d.ts(49,17): error TS2304: Cannot find name 'Promise'.
C:/Temp/AI_Contester/web/typings/whatwg-fetch/whatwg-fetch.d.ts(50,10): error TS2304: Cannot find name 'Promise'.
C:/Temp/AI_Contester/web/typings/whatwg-fetch/whatwg-fetch.d.ts(51,14): error TS2304: Cannot find name 'Promise'.
C:/Temp/AI_Contester/web/typings/whatwg-fetch/whatwg-fetch.d.ts(52,10): error TS2304: Cannot find name 'Promise'.
C:/Temp/AI_Contester/web/typings/whatwg-fetch/whatwg-fetch.d.ts(53,13): error TS2304: Cannot find name 'Promise'.
C:/Temp/AI_Contester/web/typings/whatwg-fetch/whatwg-fetch.d.ts(54,10): error TS2304: Cannot find name 'Promise'.
C:/Temp/AI_Contester/web/typings/whatwg-fetch/whatwg-fetch.d.ts(82,50): error TS2304: Cannot find name 'Promise'.
```

**Comment by easimonenko** [comment]
To avoid issues with compiling to **ES5** with the Promise, you need to install and use the package **es6-promise**.

**Comment by easimonenko** [comment]
Released Firefox **45**. As promised, classes are supported. An application to **work with ES6**.

**Comment by 2DKot** [comment]
Thank you for help!
